# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_face.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Face_display(object):
    def setupUi(self, Face_display):
        Face_display.setObjectName("Face_display")
        Face_display.resize(1121, 850)
        Face_display.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Face_display)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1120, 850))
        self.frame.setStyleSheet("\n"
"background-color:  rgb(42, 131, 162)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.majority = QtWidgets.QLabel(self.frame)
        self.majority.setGeometry(QtCore.QRect(10, 90, 55, 20))
        self.majority.setAutoFillBackground(False)
        self.majority.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Adobe 黑体 Std R\";")
        self.majority.setObjectName("majority")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setGeometry(QtCore.QRect(880, 10, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.photo1_label_3 = QtWidgets.QLabel(self.widget_3)
        self.photo1_label_3.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo1_label_3.sizePolicy().hasHeightForWidth())
        self.photo1_label_3.setSizePolicy(sizePolicy)
        self.photo1_label_3.setText("")
        self.photo1_label_3.setScaledContents(True)
        self.photo1_label_3.setObjectName("photo1_label_3")
        self.layoutWidget_10 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.id_label3 = QtWidgets.QLabel(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label3.sizePolicy().hasHeightForWidth())
        self.id_label3.setSizePolicy(sizePolicy)
        self.id_label3.setObjectName("id_label3")
        self.horizontalLayout_5.addWidget(self.id_label3)
        self.id3 = QtWidgets.QLabel(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id3.sizePolicy().hasHeightForWidth())
        self.id3.setSizePolicy(sizePolicy)
        self.id3.setText("")
        self.id3.setObjectName("id3")
        self.horizontalLayout_5.addWidget(self.id3)
        self.layoutWidget_11 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget_11.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.name_label3 = QtWidgets.QLabel(self.layoutWidget_11)
        self.name_label3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label3.sizePolicy().hasHeightForWidth())
        self.name_label3.setSizePolicy(sizePolicy)
        self.name_label3.setObjectName("name_label3")
        self.horizontalLayout_6.addWidget(self.name_label3)
        self.name3 = QtWidgets.QLabel(self.layoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name3.sizePolicy().hasHeightForWidth())
        self.name3.setSizePolicy(sizePolicy)
        self.name3.setText("")
        self.name3.setObjectName("name3")
        self.horizontalLayout_6.addWidget(self.name3)
        self.widget_4 = QtWidgets.QWidget(self.frame)
        self.widget_4.setGeometry(QtCore.QRect(340, 280, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.photo1_label_4 = QtWidgets.QLabel(self.widget_4)
        self.photo1_label_4.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo1_label_4.sizePolicy().hasHeightForWidth())
        self.photo1_label_4.setSizePolicy(sizePolicy)
        self.photo1_label_4.setText("")
        self.photo1_label_4.setScaledContents(True)
        self.photo1_label_4.setObjectName("photo1_label_4")
        self.layoutWidget_18 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget_18.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_18)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.id_label4 = QtWidgets.QLabel(self.layoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label4.sizePolicy().hasHeightForWidth())
        self.id_label4.setSizePolicy(sizePolicy)
        self.id_label4.setObjectName("id_label4")
        self.horizontalLayout_13.addWidget(self.id_label4)
        self.id4 = QtWidgets.QLabel(self.layoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id4.sizePolicy().hasHeightForWidth())
        self.id4.setSizePolicy(sizePolicy)
        self.id4.setText("")
        self.id4.setObjectName("id4")
        self.horizontalLayout_13.addWidget(self.id4)
        self.layoutWidget_19 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget_19.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_19)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.name_label4 = QtWidgets.QLabel(self.layoutWidget_19)
        self.name_label4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label4.sizePolicy().hasHeightForWidth())
        self.name_label4.setSizePolicy(sizePolicy)
        self.name_label4.setObjectName("name_label4")
        self.horizontalLayout_14.addWidget(self.name_label4)
        self.name4 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name4.sizePolicy().hasHeightForWidth())
        self.name4.setSizePolicy(sizePolicy)
        self.name4.setText("")
        self.name4.setObjectName("name4")
        self.horizontalLayout_14.addWidget(self.name4)
        self.preButton = QtWidgets.QPushButton(self.frame)
        self.preButton.setGeometry(QtCore.QRect(550, 810, 50, 40))
        self.preButton.setStyleSheet("QPushButton{border-image: url(:/new/res/vertical right.png)}QPushButton:hover{border-image: url(:/new/res/step-backward.png)}\n"
"QPushButton:pressed{border-image: url(:/new/res/step-backward.png)}\n"
"")
        self.preButton.setText("")
        self.preButton.setObjectName("preButton")
        self.widget_7 = QtWidgets.QWidget(self.frame)
        self.widget_7.setGeometry(QtCore.QRect(340, 550, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_7.setObjectName("widget_7")
        self.photo1_label_7 = QtWidgets.QLabel(self.widget_7)
        self.photo1_label_7.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo1_label_7.sizePolicy().hasHeightForWidth())
        self.photo1_label_7.setSizePolicy(sizePolicy)
        self.photo1_label_7.setText("")
        self.photo1_label_7.setScaledContents(True)
        self.photo1_label_7.setObjectName("photo1_label_7")
        self.layoutWidget_14 = QtWidgets.QWidget(self.widget_7)
        self.layoutWidget_14.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.id_label7 = QtWidgets.QLabel(self.layoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label7.sizePolicy().hasHeightForWidth())
        self.id_label7.setSizePolicy(sizePolicy)
        self.id_label7.setObjectName("id_label7")
        self.horizontalLayout_9.addWidget(self.id_label7)
        self.id7 = QtWidgets.QLabel(self.layoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id7.sizePolicy().hasHeightForWidth())
        self.id7.setSizePolicy(sizePolicy)
        self.id7.setText("")
        self.id7.setObjectName("id7")
        self.horizontalLayout_9.addWidget(self.id7)
        self.layoutWidget_15 = QtWidgets.QWidget(self.widget_7)
        self.layoutWidget_15.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.name_label7 = QtWidgets.QLabel(self.layoutWidget_15)
        self.name_label7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label7.sizePolicy().hasHeightForWidth())
        self.name_label7.setSizePolicy(sizePolicy)
        self.name_label7.setObjectName("name_label7")
        self.horizontalLayout_10.addWidget(self.name_label7)
        self.name_7 = QtWidgets.QLabel(self.layoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_7.sizePolicy().hasHeightForWidth())
        self.name_7.setSizePolicy(sizePolicy)
        self.name_7.setText("")
        self.name_7.setObjectName("name_7")
        self.horizontalLayout_10.addWidget(self.name_7)
        self.widget_5 = QtWidgets.QWidget(self.frame)
        self.widget_5.setGeometry(QtCore.QRect(610, 280, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.photo1_label_5 = QtWidgets.QLabel(self.widget_5)
        self.photo1_label_5.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo1_label_5.sizePolicy().hasHeightForWidth())
        self.photo1_label_5.setSizePolicy(sizePolicy)
        self.photo1_label_5.setText("")
        self.photo1_label_5.setScaledContents(True)
        self.photo1_label_5.setObjectName("photo1_label_5")
        self.layoutWidget_16 = QtWidgets.QWidget(self.widget_5)
        self.layoutWidget_16.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.id_label5 = QtWidgets.QLabel(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label5.sizePolicy().hasHeightForWidth())
        self.id_label5.setSizePolicy(sizePolicy)
        self.id_label5.setObjectName("id_label5")
        self.horizontalLayout_11.addWidget(self.id_label5)
        self.id5 = QtWidgets.QLabel(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id5.sizePolicy().hasHeightForWidth())
        self.id5.setSizePolicy(sizePolicy)
        self.id5.setText("")
        self.id5.setObjectName("id5")
        self.horizontalLayout_11.addWidget(self.id5)
        self.layoutWidget_17 = QtWidgets.QWidget(self.widget_5)
        self.layoutWidget_17.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.name_label5 = QtWidgets.QLabel(self.layoutWidget_17)
        self.name_label5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label5.sizePolicy().hasHeightForWidth())
        self.name_label5.setSizePolicy(sizePolicy)
        self.name_label5.setObjectName("name_label5")
        self.horizontalLayout_12.addWidget(self.name_label5)
        self.name5 = QtWidgets.QLabel(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name5.sizePolicy().hasHeightForWidth())
        self.name5.setSizePolicy(sizePolicy)
        self.name5.setText("")
        self.name5.setObjectName("name5")
        self.horizontalLayout_12.addWidget(self.name5)
        self.nextButton = QtWidgets.QPushButton(self.frame)
        self.nextButton.setGeometry(QtCore.QRect(840, 810, 50, 40))
        self.nextButton.setStyleSheet("QPushButton{border-image: url(:/new/res/vertical left.png)}QPushButton:hover{border-image: url(:/new/res/step-forward.png)}\n"
"QPushButton:pressed{border-image: url(:/new/res/step-forward.png)}\n"
"")
        self.nextButton.setText("")
        self.nextButton.setObjectName("nextButton")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(610, 10, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.photo1_label2 = QtWidgets.QLabel(self.widget_2)
        self.photo1_label2.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo1_label2.sizePolicy().hasHeightForWidth())
        self.photo1_label2.setSizePolicy(sizePolicy)
        self.photo1_label2.setText("")
        self.photo1_label2.setScaledContents(True)
        self.photo1_label2.setObjectName("photo1_label2")
        self.layoutWidget_20 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget_20.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_20)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.id_label2 = QtWidgets.QLabel(self.layoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label2.sizePolicy().hasHeightForWidth())
        self.id_label2.setSizePolicy(sizePolicy)
        self.id_label2.setObjectName("id_label2")
        self.horizontalLayout_15.addWidget(self.id_label2)
        self.id2 = QtWidgets.QLabel(self.layoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id2.sizePolicy().hasHeightForWidth())
        self.id2.setSizePolicy(sizePolicy)
        self.id2.setText("")
        self.id2.setObjectName("id2")
        self.horizontalLayout_15.addWidget(self.id2)
        self.layoutWidget_21 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget_21.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_21)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.name_label2 = QtWidgets.QLabel(self.layoutWidget_21)
        self.name_label2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label2.sizePolicy().hasHeightForWidth())
        self.name_label2.setSizePolicy(sizePolicy)
        self.name_label2.setObjectName("name_label2")
        self.horizontalLayout_16.addWidget(self.name_label2)
        self.name2 = QtWidgets.QLabel(self.layoutWidget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name2.sizePolicy().hasHeightForWidth())
        self.name2.setSizePolicy(sizePolicy)
        self.name2.setText("")
        self.name2.setObjectName("name2")
        self.horizontalLayout_16.addWidget(self.name2)
        self.widget_6 = QtWidgets.QWidget(self.frame)
        self.widget_6.setGeometry(QtCore.QRect(880, 280, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_6.setObjectName("widget_6")
        self.photo1_label_6 = QtWidgets.QLabel(self.widget_6)
        self.photo1_label_6.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo1_label_6.sizePolicy().hasHeightForWidth())
        self.photo1_label_6.setSizePolicy(sizePolicy)
        self.photo1_label_6.setText("")
        self.photo1_label_6.setScaledContents(True)
        self.photo1_label_6.setObjectName("photo1_label_6")
        self.layoutWidget_8 = QtWidgets.QWidget(self.widget_6)
        self.layoutWidget_8.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.id_label6 = QtWidgets.QLabel(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label6.sizePolicy().hasHeightForWidth())
        self.id_label6.setSizePolicy(sizePolicy)
        self.id_label6.setObjectName("id_label6")
        self.horizontalLayout_3.addWidget(self.id_label6)
        self.id6 = QtWidgets.QLabel(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id6.sizePolicy().hasHeightForWidth())
        self.id6.setSizePolicy(sizePolicy)
        self.id6.setText("")
        self.id6.setObjectName("id6")
        self.horizontalLayout_3.addWidget(self.id6)
        self.layoutWidget_9 = QtWidgets.QWidget(self.widget_6)
        self.layoutWidget_9.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.name_label6 = QtWidgets.QLabel(self.layoutWidget_9)
        self.name_label6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label6.sizePolicy().hasHeightForWidth())
        self.name_label6.setSizePolicy(sizePolicy)
        self.name_label6.setObjectName("name_label6")
        self.horizontalLayout_4.addWidget(self.name_label6)
        self.name_6 = QtWidgets.QLabel(self.layoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_6.sizePolicy().hasHeightForWidth())
        self.name_6.setSizePolicy(sizePolicy)
        self.name_6.setText("")
        self.name_6.setObjectName("name_6")
        self.horizontalLayout_4.addWidget(self.name_6)
        self.school = QtWidgets.QLabel(self.frame)
        self.school.setGeometry(QtCore.QRect(10, 60, 55, 20))
        self.school.setAutoFillBackground(False)
        self.school.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Adobe 黑体 Std R\";")
        self.school.setObjectName("school")
        self.widget_8 = QtWidgets.QWidget(self.frame)
        self.widget_8.setGeometry(QtCore.QRect(610, 550, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_8.setObjectName("widget_8")
        self.photo1_label_8 = QtWidgets.QLabel(self.widget_8)
        self.photo1_label_8.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo1_label_8.sizePolicy().hasHeightForWidth())
        self.photo1_label_8.setSizePolicy(sizePolicy)
        self.photo1_label_8.setText("")
        self.photo1_label_8.setScaledContents(True)
        self.photo1_label_8.setObjectName("photo1_label_8")
        self.layoutWidget_12 = QtWidgets.QWidget(self.widget_8)
        self.layoutWidget_12.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.id_label8 = QtWidgets.QLabel(self.layoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label8.sizePolicy().hasHeightForWidth())
        self.id_label8.setSizePolicy(sizePolicy)
        self.id_label8.setObjectName("id_label8")
        self.horizontalLayout_7.addWidget(self.id_label8)
        self.id8 = QtWidgets.QLabel(self.layoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id8.sizePolicy().hasHeightForWidth())
        self.id8.setSizePolicy(sizePolicy)
        self.id8.setText("")
        self.id8.setObjectName("id8")
        self.horizontalLayout_7.addWidget(self.id8)
        self.layoutWidget_13 = QtWidgets.QWidget(self.widget_8)
        self.layoutWidget_13.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.name_label8 = QtWidgets.QLabel(self.layoutWidget_13)
        self.name_label8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label8.sizePolicy().hasHeightForWidth())
        self.name_label8.setSizePolicy(sizePolicy)
        self.name_label8.setObjectName("name_label8")
        self.horizontalLayout_8.addWidget(self.name_label8)
        self.name8 = QtWidgets.QLabel(self.layoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name8.sizePolicy().hasHeightForWidth())
        self.name8.setSizePolicy(sizePolicy)
        self.name8.setText("")
        self.name8.setObjectName("name8")
        self.horizontalLayout_8.addWidget(self.name8)
        self.widget_9 = QtWidgets.QWidget(self.frame)
        self.widget_9.setGeometry(QtCore.QRect(880, 550, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_9.setObjectName("widget_9")
        self.photo1_label_9 = QtWidgets.QLabel(self.widget_9)
        self.photo1_label_9.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo1_label_9.sizePolicy().hasHeightForWidth())
        self.photo1_label_9.setSizePolicy(sizePolicy)
        self.photo1_label_9.setText("")
        self.photo1_label_9.setScaledContents(True)
        self.photo1_label_9.setObjectName("photo1_label_9")
        self.layoutWidget_6 = QtWidgets.QWidget(self.widget_9)
        self.layoutWidget_6.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.id_label9 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label9.sizePolicy().hasHeightForWidth())
        self.id_label9.setSizePolicy(sizePolicy)
        self.id_label9.setObjectName("id_label9")
        self.horizontalLayout_2.addWidget(self.id_label9)
        self.id9 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id9.sizePolicy().hasHeightForWidth())
        self.id9.setSizePolicy(sizePolicy)
        self.id9.setText("")
        self.id9.setObjectName("id9")
        self.horizontalLayout_2.addWidget(self.id9)
        self.layoutWidget_7 = QtWidgets.QWidget(self.widget_9)
        self.layoutWidget_7.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label9 = QtWidgets.QLabel(self.layoutWidget_7)
        self.name_label9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label9.sizePolicy().hasHeightForWidth())
        self.name_label9.setSizePolicy(sizePolicy)
        self.name_label9.setObjectName("name_label9")
        self.horizontalLayout.addWidget(self.name_label9)
        self.name9 = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name9.sizePolicy().hasHeightForWidth())
        self.name9.setSizePolicy(sizePolicy)
        self.name9.setText("")
        self.name9.setObjectName("name9")
        self.horizontalLayout.addWidget(self.name9)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(60, 130, 261, 691))
        self.listWidget.setStyleSheet("font: 12pt \"Adobe 黑体 Std R\";\n"
"color:rgb(173,175,178); background:rgb(25,27,31);border:0px solid gray;}\n"
"QListWidget::Item{height:30px;border:0px solid gray;padding-left:15;}\n"
"QListWidget::Item:hover{color:rgb(0,0,0);background:transparent;border:0px solid gray;}\n"
"QListWidget::Item:selected{border-image:url(images/listwidget_h.png); color:rgb(255,255,255);\n"
"border:0px solid gray;\n"
"QListWidget::Item:selected:active{background:#00FFFFFF;color:#FFFFFF;border-width:0;}")
        self.listWidget.setObjectName("listWidget")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(60, 90, 251, 25))
        self.comboBox_2.setStyleSheet("font: 12pt \"Adobe 黑体 Std R\";\n"
"color:rgb(223, 223, 223)")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(60, 60, 251, 25))
        self.comboBox.setStyleSheet("font: 12pt \"Adobe 黑体 Std R\";\n"
"color:rgb(223, 223, 223)")
        self.comboBox.setObjectName("comboBox")
        self.widget_1 = QtWidgets.QWidget(self.frame)
        self.widget_1.setGeometry(QtCore.QRect(340, 10, 251, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(sizePolicy)
        self.widget_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.widget_1.setObjectName("widget_1")
        self.photo_label1 = QtWidgets.QLabel(self.widget_1)
        self.photo_label1.setGeometry(QtCore.QRect(0, 0, 220, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.photo_label1.sizePolicy().hasHeightForWidth())
        self.photo_label1.setSizePolicy(sizePolicy)
        self.photo_label1.setStyleSheet("")
        self.photo_label1.setText("")
        self.photo_label1.setScaledContents(True)
        self.photo_label1.setObjectName("photo_label1")
        self.layoutWidget_22 = QtWidgets.QWidget(self.widget_1)
        self.layoutWidget_22.setGeometry(QtCore.QRect(2, 222, 201, 19))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_22)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.id_label1 = QtWidgets.QLabel(self.layoutWidget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_label1.sizePolicy().hasHeightForWidth())
        self.id_label1.setSizePolicy(sizePolicy)
        self.id_label1.setObjectName("id_label1")
        self.horizontalLayout_17.addWidget(self.id_label1)
        self.id1 = QtWidgets.QLabel(self.layoutWidget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id1.sizePolicy().hasHeightForWidth())
        self.id1.setSizePolicy(sizePolicy)
        self.id1.setText("")
        self.id1.setObjectName("id1")
        self.horizontalLayout_17.addWidget(self.id1)
        self.layoutWidget_23 = QtWidgets.QWidget(self.widget_1)
        self.layoutWidget_23.setGeometry(QtCore.QRect(2, 248, 201, 19))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_23)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.name_label1 = QtWidgets.QLabel(self.layoutWidget_23)
        self.name_label1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label1.sizePolicy().hasHeightForWidth())
        self.name_label1.setSizePolicy(sizePolicy)
        self.name_label1.setObjectName("name_label1")
        self.horizontalLayout_18.addWidget(self.name_label1)
        self.name1 = QtWidgets.QLabel(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name1.sizePolicy().hasHeightForWidth())
        self.name1.setSizePolicy(sizePolicy)
        self.name1.setText("")
        self.name1.setObjectName("name1")
        self.horizontalLayout_18.addWidget(self.name1)
        self.class_2 = QtWidgets.QLabel(self.frame)
        self.class_2.setGeometry(QtCore.QRect(10, 120, 55, 20))
        self.class_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Adobe 黑体 Std R\";")
        self.class_2.setObjectName("class_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 20, 201, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.backButton = QtWidgets.QPushButton(self.layoutWidget)
        self.backButton.setStyleSheet("\n"
"\n"
"QPushButton{color: rgb(0,0,0);\n"
"border-image: url(:/new/res/43.gif);\n"
"font: 25 12pt \"微软雅黑 Light\";\n"
"border:2px groove gray;\n"
"border-radius:15px;\n"
"padding:4px 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(22, 94, 131);\n"
"border-image: url(:/new/res/46.gif);color: rgb(0, 255, 255);\n"
"font: 25 12pt \"微软雅黑 Light\";\n"
"border:2px groove gray;\n"
"border-radius:15px;\n"
"padding:4px 4px;}\n"
"QPushButton:pressed{\n"
"border-image: url(:/new/res/46.gif);color: rgb(0, 255, 255);\n"
"font: 25 12pt \"微软雅黑 Light\";\n"
"border:2px groove gray;\n"
"border-radius:15px;\n"
"padding:4px 4px;}\n"
"")
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_19.addWidget(self.backButton)
        self.addstuButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addstuButton.setStyleSheet("\n"
"\n"
"QPushButton{color: rgb(0,0,0);\n"
"border-image: url(:/new/res/43.gif);\n"
"font: 25 12pt \"微软雅黑 Light\";\n"
"border:2px groove gray;\n"
"border-radius:15px;\n"
"padding:4px 4px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(22, 94, 131);\n"
"border-image: url(:/new/res/46.gif);color: rgb(0, 255, 255);\n"
"font: 25 12pt \"微软雅黑 Light\";\n"
"border:2px groove gray;\n"
"border-radius:15px;\n"
"padding:4px 4px;}\n"
"QPushButton:pressed{\n"
"border-image: url(:/new/res/46.gif);color: rgb(0, 255, 255);\n"
"font: 25 12pt \"微软雅黑 Light\";\n"
"border:2px groove gray;\n"
"border-radius:15px;\n"
"padding:4px 4px;}\n"
"")
        self.addstuButton.setObjectName("addstuButton")
        self.horizontalLayout_19.addWidget(self.addstuButton)
        self.majority.raise_()
        self.widget_3.raise_()
        self.widget_4.raise_()
        self.widget_7.raise_()
        self.widget_5.raise_()
        self.widget_2.raise_()
        self.widget_6.raise_()
        self.school.raise_()
        self.widget_8.raise_()
        self.widget_9.raise_()
        self.listWidget.raise_()
        self.comboBox_2.raise_()
        self.comboBox.raise_()
        self.widget_1.raise_()
        self.class_2.raise_()
        self.layoutWidget.raise_()
        self.preButton.raise_()
        self.nextButton.raise_()

        self.retranslateUi(Face_display)
        QtCore.QMetaObject.connectSlotsByName(Face_display)

    def retranslateUi(self, Face_display):
        _translate = QtCore.QCoreApplication.translate
        Face_display.setWindowTitle(_translate("Face_display", "Form"))
        self.majority.setText(_translate("Face_display", "专业："))
        self.id_label3.setText(_translate("Face_display", "学号:"))
        self.name_label3.setText(_translate("Face_display", "姓名:"))
        self.id_label4.setText(_translate("Face_display", "学号:"))
        self.name_label4.setText(_translate("Face_display", "姓名:"))
        self.preButton.setToolTip(_translate("Face_display", "<html><head/><body><p><span style=\" font-size:10pt;\">上一页</span></p></body></html>"))
        self.id_label7.setText(_translate("Face_display", "学号:"))
        self.name_label7.setText(_translate("Face_display", "姓名:"))
        self.id_label5.setText(_translate("Face_display", "学号:"))
        self.name_label5.setText(_translate("Face_display", "姓名:"))
        self.nextButton.setToolTip(_translate("Face_display", "<html><head/><body><p><span style=\" font-size:10pt;\">下一页</span></p></body></html>"))
        self.id_label2.setText(_translate("Face_display", "学号:"))
        self.name_label2.setText(_translate("Face_display", "姓名:"))
        self.id_label6.setText(_translate("Face_display", "学号:"))
        self.name_label6.setText(_translate("Face_display", "姓名:"))
        self.school.setText(_translate("Face_display", "学院："))
        self.id_label8.setText(_translate("Face_display", "学号:"))
        self.name_label8.setText(_translate("Face_display", "姓名:"))
        self.id_label9.setText(_translate("Face_display", "学号:"))
        self.name_label9.setText(_translate("Face_display", "姓名:"))
        self.id_label1.setText(_translate("Face_display", "学号:"))
        self.name_label1.setText(_translate("Face_display", "姓名:"))
        self.class_2.setText(_translate("Face_display", "班级："))
        self.backButton.setText(_translate("Face_display", "返回"))
        self.addstuButton.setText(_translate("Face_display", "录入/更新照片"))

import photo_rc
